### ISSUE TITLE
TTS data preparation from News data

### ISSUE THREAD

**Issue by kaldan007** [OpenPecha/news-audio-data#2]
**Description**:
 We currently have news full audio and corresponding news transcript. We would like to get the news text and audio data split into segments to train our STT and TTS model.

**Implementation**:

**Subtask**:

- [ ] update voa meta data with news reader name
- [ ] delete the extra audio file
- [ ] prepare catalog as per ganga suggestion
- [ ] Spit audio into segments
- [ ] Run inference in audio
- [ ] Transfer news transcript

**Comment by kaldan007** [comment]
please run on two point catalog

**Comment by tenzinchoedon** [comment]
Sr. no 	ID 	Audio link	Audio text link	Audio Duration  (hh:mm:ss)	Speaker name	Speaker Gender	News channel	Publishing Year

**Comment by tenzinchoedon** [comment]
Link to the Google Sheet: https://docs.google.com/spreadsheets/d/1732g2pCbeuTUGjtep_V-8vaKAGzTK41662ehGepGdSQ/edit?usp=sharing

**Comment by kaldan007** [comment]
@tenzinchoedon can u explore any existing lib to diff between male and female audio
